// Duplicate library entries (hidden name -> kept name). Mirrors exercises.alias_of
// (migration 20261003b_library_cleanup.sql). Hidden entries stay in the DB so old plans and
// logs keep resolving; pickers hide them and imports log under the kept name.
export const EXERCISE_ALIASES: Record<string, string> = {
  "Push-ups": "Liegestütze",
  "Rudern": "Rudern (Langhantel)",
  "Kurzhantel Bizeps Curls": "Bizeps Curls",
  "Kurzhantel Concentration Curl": "Concentration Curls",
  "Elliptical Crosstrainer": "Crosstrainer",
  "Kabel Latzug": "Latzug",
  "Kabel Latzug (Stange)": "Latzug",
  "Kabel Pushdown": "Trizepsdrücken",
  "Kurzhantel Seitheben": "Seitheben",
  "Kurzhantel Frontheben": "Frontheben",
  "Kurzhantel Frontheben (V2)": "Frontheben",
  "Langhantel Upright Row": "Upright Row",
  "Langhantel Upright Row (V3)": "Upright Row",
  "Kurzhantel Step-ups": "Step-ups",
  "Hängen Gestreckt Bein-Hüft Heben": "Hanging Leg Raises",
  "Jump Squat (V2)": "Jump Squats",
  "Langhantel Close-Grip Bankdrücken": "Close Grip Bankdrücken",
  "Langhantel Liegend Trizeps Extension": "Skull Crusher",
  "Langhantel Front Kniebeuge": "Frontkniebeugen",
  "Kurzhantel Ausfallschritte": "Ausfallschritte",
  "Maschine Stehend Wadenheben": "Wadenheben",
  "Einbein Wadenheben (Kurzhantel)": "Kurzhantel Einbein Wadenheben",
  "Bizeps Klimmzüge": "Chin-ups",
  "Langhantel Glute Bridge (Bank, beide Beine)": "Hip Thrusts",
  "Tiefer Glute Bridge am Boden": "Glute Bridges",
  "Hüftheben (Knie gebeugt)": "Glute Bridges",
  "Stationäres Fahrrad Laufen (V3)": "Stationäres Fahrrad",
  "Kabel Tief Sitz Rudern": "Sitzrudern (Kabel)",
  "Kabel Boden Sitz Rudern (breit)": "Kabel Sitz Rudern (breiter Griff)",
  "Kurzhantel Gerade-Bein Kreuzheben": "Kurzhantel Steifbein Kreuzheben",
  "Kabel Stehender Fly": "Cable Fly",
  "Kabel Crossover Variante": "Cable Crossover",
  "Langhantel Preacher Curl": "Preacher Curls",
  "Kabel Stehend Crossover Reverse Fly": "Reverse Fly",
  "Kabel Rear Delt Rudern (Seil)": "Kabel Stehend Rear Delt Rudern (Seil)",
  "Kabel Vorheben": "Kabel Frontheben",
  "Kabel Gerade-Arm Latzug": "Straight Arm Pulldown",
  "Langhantel Wrist Curl": "Wrist Curls",
  "Langhantel Wrist Curl (V2)": "Wrist Curls",
  "Kurzhantel Über Bank Einarmig Wrist Curl": "Kurzhantel Einarmig Wrist Curl",
  "Langhantel Bank Kniebeuge": "Box Squat",
  "Langhantel Steifbein Good Morning": "Good Mornings",
  "Kurzhantel Gerade-Arm Pullover": "Kurzhantel Pullover",
  "Kurzhantel Step-up Ausfallschritt (V2)": "Kurzhantel Step-up Ausfallschritt",
  "Langhantel Hintere Ausfallschritte (V2)": "Langhantel Hintere Ausfallschritte",
  "Langhantel Kniebeuge-Sprung Ausfallschritt (V2)": "Langhantel Kniebeuge-Sprung Ausfallschritt",
  "Langhantel Side Split Kniebeuge (V2)": "Langhantel Side Split Kniebeuge",
  "Kurzhantel Liegend Einarmig Drücken (V2)": "Kurzhantel Liegend Einarmig Drücken",
  "Kurzhantel Sumo Pull Through (V2)": "Kurzhantel Sumo Pull Through",
  "Kurzhantel Decline Schulterheben (V2)": "Kurzhantel Decline Schulterheben",
};

export const canonicalExercise = (name: string): string => EXERCISE_ALIASES[name] ?? name;
