-- 96 more new exercises (incl. new group 'Mobilitaet' for stretching/yoga/warm-up) - every remaining Vital clip that is not a duplicate.
-- Only INSERTs into the shared exercise library: existing exercises, plans, logs and accounts are untouched.
-- Skips any name that already exists, so it is safe to run twice.
-- Non-ASCII text is written as Unicode escapes (U&'...') so umlauts survive copy/paste into the SQL editor.
-- exercise_id 'va<clip>' is informational; the app finds the animation by exercise name (src/lib/demoVideos.ts).

begin;

insert into exercises (name, muscle_group, equipment, tempo, default_sets, default_reps, default_rest_sec, exercise_id, cues)
select v.* from (values
  (U&'Kettlebell Sit-up mit Dr\00FCcken', 'Core', 'Kettlebell', '2-1-2', 3, 10, 60, 'va0005', ARRAY['Bauch anspannen', U&'\00DCber Kopf strecken', 'Kontrolliert absenken']),
  ('Plank mit Gewicht', 'Core', 'Zusatzgewicht', 'Halten', 3, 30, 60, 'va0006', ARRAY[U&'Gerader K\00F6rper', U&'Po nicht durchh\00E4ngen', 'Spannung halten']),
  ('Plank (gestreckte Arme)', 'Core', U&'K\00F6rpergewicht', 'Halten', 3, 30, 45, 'va0156', ARRAY['Hohe Brettstellung', U&'Gerader K\00F6rper', 'Spannung halten']),
  (U&'Plank (F\00FC\00DFe erh\00F6ht)', 'Core', U&'K\00F6rpergewicht', 'Halten', 3, 30, 45, 'va0107', ARRAY['Ellenbogen unter Schultern', U&'Gerader K\00F6rper', 'Spannung halten']),
  ('Dolphin Plank', 'Core', U&'K\00F6rpergewicht', 'Halten', 3, 30, 45, 'va1129', ARRAY['Ellenbogen unter Schultern', U&'H\00FCfte angehoben', 'Spannung halten']),
  ('Plank Kurzhantel-Durchzug', 'Core', 'Kurzhantel', '2-1-2', 3, 10, 60, 'va0109', ARRAY['Hohe Brettstellung', U&'H\00FCfte stabil', 'Seiten abwechseln']),
  ('Side Plank mit Armheben', 'Core', U&'K\00F6rpergewicht', '2-1-2', 3, 10, 45, 'va0168', ARRAY[U&'Seitliche St\00FCtze', U&'H\00FCfte angehoben', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Plank Jacks', 'Cardio', U&'K\00F6rpergewicht', 'Schnell', 3, 20, 45, 'va1177', ARRAY['Hohe Brettstellung', U&'H\00FCfte stabil', 'Rhythmus halten']),
  ('Mountain Climbers diagonal', 'Core', U&'K\00F6rpergewicht', 'Schnell', 3, 20, 45, 'va0104', ARRAY['Hohe Brettstellung', 'Knie abwechselnd zur Brust', 'Rumpf stabil']),
  ('Russian Twists (ohne Gewicht)', 'Core', U&'K\00F6rpergewicht', '2-0-2', 3, 20, 45, 'va0122', ARRAY[U&'Oberk\00F6rper zur\00FCckgelehnt', U&'F\00FC\00DFe angehoben', 'Seiten abwechseln']),
  ('Sit-ups mit Drehung', 'Core', U&'K\00F6rpergewicht', '2-1-2', 3, 15, 45, 'va1203', ARRAY['Bauch anspannen', 'Kontrolliert drehen', 'Seiten abwechseln']),
  ('Bird Dog (fortgeschritten)', 'Core', U&'K\00F6rpergewicht', '2-2-2', 3, 10, 45, 'va1110', ARRAY[U&'R\00FCcken gerade', 'Rumpf stabil', 'Gleichgewicht halten']),
  ('Langhantel Marsch', 'Core', 'Langhantel', '2-1-2', 3, 20, 60, 'va0058', ARRAY[U&'Oberk\00F6rper aufrecht', 'Rumpf anspannen', 'Knie abwechselnd zur Brust']),
  ('Kurzhantel Marsch', 'Core', 'Kurzhantel', '2-1-2', 3, 20, 60, 'va0255', ARRAY[U&'Oberk\00F6rper aufrecht', 'Rumpf anspannen', 'Knie abwechselnd zur Brust']),
  ('Kettlebell Marsch', 'Core', 'Kettlebell', '2-1-2', 3, 20, 60, 'va0070', ARRAY[U&'Oberk\00F6rper aufrecht', 'Rumpf anspannen', 'Knie abwechselnd zur Brust']),
  ('Langhantel Halten', 'Unterarme', 'Langhantel', 'Halten', 3, 30, 60, 'va0010', ARRAY['Griff fest', 'Schultern unten', 'Spannung halten']),
  ('Kettlebell Einarmig Hochziehen', 'Schultern', 'Kettlebell', '2-1-2', 3, 10, 60, 'va0071', ARRAY['Ellenbogen hoch', U&'Gewicht nah am K\00F6rper', U&'Gleichm\00E4\00DFig beide Seiten']),
  (U&'Widerstandsband Liegest\00FCtze', 'Brust', 'Widerstandsband', '2-1-1', 3, 12, 60, 'va0008', ARRAY[U&'Gerader K\00F6rper', 'Brust fast zum Boden', U&'Explosiv dr\00FCcken']),
  (U&'Liegest\00FCtze an Kurzhanteln', 'Brust', 'Kurzhantel', '2-1-1', 3, 12, 60, 'va0027', ARRAY['Griff fest', U&'Gerader K\00F6rper', 'Brust fast zum Boden']),
  (U&'Liegest\00FCtze mit Armheben', 'Brust', U&'K\00F6rpergewicht', '2-1-1', 3, 10, 60, 'va0160', ARRAY[U&'Gerader K\00F6rper', U&'H\00FCfte stabil', 'Seiten abwechseln']),
  (U&'Fingerspitzen-Liegest\00FCtze', 'Brust', U&'K\00F6rpergewicht', '2-1-1', 3, 8, 60, 'va0226', ARRAY[U&'Gerader K\00F6rper', 'Spannung halten', 'Kontrolliert absenken']),
  (U&'Faust-Liegest\00FCtze', 'Brust', U&'K\00F6rpergewicht', '2-1-1', 3, 12, 60, 'va1157', ARRAY[U&'Gerader K\00F6rper', 'Brust fast zum Boden', U&'Explosiv dr\00FCcken']),
  (U&'Einarmige Liegest\00FCtze', 'Brust', U&'K\00F6rpergewicht', '3-1-1', 3, 5, 90, 'va0233', ARRAY[U&'K\00F6rper anspannen', 'Gleichgewicht halten', U&'Gleichm\00E4\00DFig beide Seiten']),
  (U&'Liegest\00FCtze an Parallettes', 'Brust', U&'K\00F6rpergewicht', '2-1-1', 3, 10, 60, 'va0234', ARRAY[U&'Gerader K\00F6rper', U&'Tiefer als 90\00B0', U&'Explosiv dr\00FCcken']),
  ('Glute Bridge mit Brustpresse', 'Brust', 'Kurzhantel', '2-1-2', 3, 12, 60, 'va0225', ARRAY[U&'H\00FCfte anheben', 'Po anspannen', U&'Kontrolliert dr\00FCcken']),
  ('Kabel Pushdown (V-Griff)', 'Arme', 'Kabelzug', '2-1-2', 3, 12, 60, 'va0139', ARRAY[U&'Ellenbogen fest am K\00F6rper', 'Volle Streckung', U&'Kontrolliert zur\00FCck']),
  ('Kurzhantel Waiter Curl', 'Arme', 'Kurzhantel', '2-1-2', 3, 12, 60, 'va0151', ARRAY[U&'Ellenbogen fest am K\00F6rper', 'Kein Schwung', 'Bizeps anspannen']),
  ('Kurzhantel Einarmig Overhead Trizeps Extension', 'Arme', 'Kurzhantel', '2-1-2', 3, 12, 60, 'va0173', ARRAY['Ellenbogen fixiert', U&'\00DCber Kopf strecken', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Seitheben sitzend', 'Schultern', 'Kurzhantel', '2-1-2', 3, 12, 45, 'va0164', ARRAY['Aufrechter Sitz', U&'Bis Schulterh\00F6he heben', 'Kein Schwung']),
  ('Frontheben Hammergriff', 'Schultern', 'Kurzhantel', '2-1-2', 3, 12, 45, 'va0262', ARRAY['Neutralgriff', U&'Bis Schulterh\00F6he heben', 'Kein Schwung']),
  (U&'Kurzhantel Au\00DFenrotation', 'Schultern', 'Kurzhantel', '2-1-2', 3, 15, 45, 'va0288', ARRAY[U&'Ellenbogen fest am K\00F6rper', 'Leichtes Gewicht', U&'Kontrolliert zur\00FCck']),
  ('Armkreisen mit Kurzhanteln', 'Schultern', 'Kurzhantel', '2-0-2', 3, 20, 45, 'va0152', ARRAY['Leichtes Gewicht', 'Arme gestreckt', 'Kontrollierte Bewegung']),
  ('Upright Row (Untergriff)', 'Schultern', 'Langhantel', '2-1-2', 3, 12, 60, 'va0296', ARRAY['Ellenbogen hoch', U&'Gewicht nah am K\00F6rper', 'Kontrolliert absenken']),
  ('Landmine Press (beidarmig)', 'Schultern', 'Langhantel', '2-1-2', 3, 10, 60, 'va0298', ARRAY['Rumpf anspannen', U&'Kontrolliert dr\00FCcken', 'Volle Streckung']),
  (U&'Pike Liegest\00FCtze (erh\00F6ht)', 'Schultern', U&'K\00F6rpergewicht', '2-1-1', 3, 8, 90, 'va0291', ARRAY[U&'H\00FCfte nach oben', 'Kontrolliert absenken', U&'Explosiv dr\00FCcken']),
  ('Widerstandsband W-Raise', 'Schultern', 'Widerstandsband', '2-1-2', 3, 15, 45, 'va0202', ARRAY[U&'Schulterbl\00E4tter zusammen', 'Ellenbogen nach hinten', U&'Kontrolliert zur\00FCck']),
  (U&'Widerstandsband \00DCberkopf-Zug', 'Schultern', 'Widerstandsband', '2-1-2', 3, 15, 45, 'va0294', ARRAY['Arme gestreckt', U&'Schulterbl\00E4tter zusammen', U&'Kontrolliert zur\00FCck']),
  ('Rudern sitzend (Maschine, Brustauflage)', U&'R\00FCcken', 'Maschine', '2-1-2', 3, 12, 60, 'va0040', ARRAY[U&'Oberk\00F6rper stabil', U&'Schulterbl\00E4tter zusammen', U&'Kontrolliert zur\00FCck']),
  ('Gorilla Row', U&'R\00FCcken', 'Kurzhantel', '2-1-2', 3, 10, 60, 'va0193', ARRAY[U&'R\00FCcken gerade', 'Seiten abwechseln', U&'Gewicht nah am K\00F6rper']),
  (U&'R\00FCckenstrecken in Bauchlage', U&'R\00FCcken', U&'K\00F6rpergewicht', '2-1-2', 3, 15, 45, 'va0197', ARRAY[U&'R\00FCcken anspannen', U&'Nicht \00FCberstrecken', 'Kontrolliert absenken']),
  ('Widerstandsband Kreuzheben', 'Beine', 'Widerstandsband', '2-1-2', 3, 15, 45, 'va0200', ARRAY[U&'R\00FCcken gerade', U&'H\00FCfte nach hinten schieben', U&'H\00FCfte durchdr\00FCcken']),
  ('Widerstandsband Good Morning', 'Beine', 'Widerstandsband', '2-1-2', 3, 15, 45, 'va0274', ARRAY[U&'R\00FCcken gerade', U&'H\00FCfte nach hinten schieben', 'Leicht gebeugte Knie']),
  ('Widerstandsband Kniebeuge mit Beinabspreizen', 'Po', 'Widerstandsband', '2-1-2', 3, 12, 45, 'va0276', ARRAY['Knie in Linie', 'Bein zur Seite heben', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Steifbein Kreuzheben (Maschine)', 'Beine', 'Maschine', '2-1-2', 3, 10, 90, 'va0084', ARRAY[U&'R\00FCcken gerade', U&'H\00FCfte nach hinten schieben', 'Spannung in Beinbeuger']),
  (U&'Pistol Squat mit St\00FCtze', 'Beine', U&'K\00F6rpergewicht', '3-1-1', 3, 8, 60, 'va1174', ARRAY['Gleichgewicht halten', 'Kontrolliert absenken', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Depth Jumps', 'Beine', U&'K\00F6rpergewicht', 'Explosiv', 3, 6, 90, 'va1127', ARRAY['Weich landen', U&'Sofort n\00E4chste Wiederholung', 'Explosiv springen']),
  ('Laufen auf der Stelle', 'Cardio', U&'K\00F6rpergewicht', 'Schnell', 3, 60, 30, 'va0218', ARRAY['Rhythmus halten', U&'Oberk\00F6rper aufrecht', 'Atmung kontrollieren']),
  ('High Knees', 'Cardio', U&'K\00F6rpergewicht', 'Schnell', 3, 30, 30, 'va1144', ARRAY['Knie abwechselnd zur Brust', U&'Oberk\00F6rper aufrecht', 'Rhythmus halten']),
  ('High Knees mit Anfersen', 'Cardio', U&'K\00F6rpergewicht', 'Schnell', 3, 30, 30, 'va1143', ARRAY['Rhythmus halten', U&'Oberk\00F6rper aufrecht', 'Atmung kontrollieren']),
  ('Hampelmann mit Knieheben', 'Cardio', U&'K\00F6rpergewicht', 'Schnell', 3, 20, 30, 'va1154', ARRAY['Rhythmus halten', 'Weich landen', 'Atmung kontrollieren']),
  ('Hampelmann mit Band', 'Cardio', 'Widerstandsband', 'Schnell', 3, 20, 30, 'va0266', ARRAY['Rhythmus halten', 'Weich landen', 'Spannung halten']),
  ('Seitliche Sprint-Shuffles', 'Cardio', U&'K\00F6rpergewicht', 'Schnell', 3, 30, 45, 'va1159', ARRAY['Schnell wechseln', 'Leicht gebeugte Knie', 'Rhythmus halten']),
  ('Sprint-Intervalle', 'Cardio', U&'K\00F6rpergewicht', 'Schnell', 6, 20, 60, 'va1190', ARRAY[U&'Explosiv ausf\00FChren', 'Atmung kontrollieren', 'Rhythmus finden']),
  ('Katze-Kuh', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va0190', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Kindhaltung', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1118', ARRAY['Langsam dehnen', 'Kein Schmerz', 'Atmung ruhig']),
  ('Herabschauender Hund', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1130', ARRAY['Langsam dehnen', 'Kein Schmerz', 'Atmung ruhig']),
  ('Plank zu herabschauendem Hund', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va0196', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Chaturanga zu heraufschauendem Hund', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1117', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Inchworm', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1150', ARRAY['Beine gestreckt', 'Hohe Brettstellung', U&'Kontrolliert zur\00FCck']),
  ('Wirbelwelle in Kniebeuge', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1189', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Berghaltung zur Vorbeuge', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1167', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Stehende Vorbeuge', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1206', ARRAY['Langsam dehnen', 'Kein Schmerz', 'Atmung ruhig']),
  ('Halbe Vorbeuge', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1141', ARRAY[U&'R\00FCcken gerade', 'Langsam dehnen', 'Atmung ruhig']),
  ('Sitzende Vorbeuge', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1138', ARRAY['Langsam dehnen', 'Kein Schmerz', 'Atmung ruhig']),
  ('Sitzender Drehsitz', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1108', ARRAY['Langsam dehnen', 'Kein Schmerz', 'Atmung ruhig']),
  ('Dreieck', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1171', ARRAY['Langsam dehnen', 'Kein Schmerz', 'Atmung ruhig']),
  ('Krieger I', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1207', ARRAY[U&'Oberk\00F6rper aufrecht', 'Langsam dehnen', 'Atmung ruhig']),
  (U&'Schulterbr\00FCcke', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1112', ARRAY[U&'H\00FCfte anheben', 'Langsam dehnen', 'Atmung ruhig']),
  (U&'Rad (volle Br\00FCcke)', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1137', ARRAY['Langsam dehnen', 'Kein Schmerz', 'Spannung halten']),
  (U&'Thorakale Br\00FCcke', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1180', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  (U&'Kr\00E4he', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1125', ARRAY['Gleichgewicht halten', 'Spannung halten', 'Atmung ruhig']),
  (U&'Kopfstand (Dreifu\00DF)', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1202', ARRAY['Gleichgewicht halten', U&'K\00F6rper anspannen', U&'Langsam ausf\00FChren']),
  ('Kopfstand-Vorbereitung', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1160', ARRAY['Gleichgewicht halten', U&'Langsam ausf\00FChren', U&'K\00F6rper anspannen']),
  ('Unterarmstand-Flow', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1122', ARRAY['Gleichgewicht halten', U&'K\00F6rper anspannen', U&'Langsam ausf\00FChren']),
  ('Beinbeuger-Dehnung stehend', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1194', ARRAY['Langsam dehnen', 'Kein Schmerz', 'Atmung ruhig']),
  ('Beinbeuger-Dehnung mit Band', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1121', ARRAY['Langsam dehnen', 'Kein Schmerz', 'Atmung ruhig']),
  ('Quadrizeps-Dehnung stehend', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1196', ARRAY['Knie in Linie', 'Langsam dehnen', 'Gleichgewicht halten']),
  (U&'H\00FCftbeuger-Dehnung kniend', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1146', ARRAY['Langsam dehnen', 'Kein Schmerz', 'Atmung ruhig']),
  (U&'H\00FCftbeuger-Ausfallschritt', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1148', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  (U&'H\00FCftdehnung stehend', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1195', ARRAY['Langsam dehnen', 'Kein Schmerz', 'Atmung ruhig']),
  (U&'H\00FCftkreisen', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1145', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  (U&'Beinschwingen vor und zur\00FCck', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1162', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Beinschwingen seitlich', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1164', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Beinkreisen', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1163', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Armdehnung dynamisch', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1132', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  (U&'Armschwung \00FCber Kopf', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va0131', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Seitliche Rumpfdehnung', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1133', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Schulterdehnung quer', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1124', ARRAY['Langsam dehnen', 'Kein Schmerz', 'Atmung ruhig']),
  (U&'Schulterdehnung aus dem St\00FCtz', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1185', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Schulterkreisen', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1183', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Schulter-CARs', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1182', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Schulterrollen mit Band', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va0295', ARRAY['Kontrollierte Bewegung', 'Atmung ruhig', U&'Gleichm\00E4\00DFig beide Seiten']),
  ('Nackenkreisen', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', '2-0-2', 2, 10, 15, 'va1168', ARRAY[U&'Langsam ausf\00FChren', 'Kein Schmerz', 'Atmung ruhig']),
  ('Erholungsatmung', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1198', ARRAY['Atmung ruhig', 'Rumpf anspannen', U&'Langsam ausf\00FChren']),
  ('Kapalabhati-Atmung', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1156', ARRAY['Atmung kontrollieren', 'Bauch anspannen', 'Rhythmus halten']),
  ('Ujjayi-Atmung', U&'Mobilit\00E4t', U&'K\00F6rpergewicht', 'Halten', 2, 30, 15, 'va1204', ARRAY['Atmung ruhig', 'Rhythmus halten', U&'Langsam ausf\00FChren'])
) as v(name, muscle_group, equipment, tempo, default_sets, default_reps, default_rest_sec, exercise_id, cues)
where not exists (select 1 from exercises e where e.name = v.name);

commit;

-- Check: should print 167 (71 from the first batch + 96 from this one)
select count(*) from exercises where exercise_id like 'va%';
